# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyhelm < Formula
  desc "A terminal UI for browsing and managing Helm charts"
  homepage "https://github.com/alessandropitocchi/lazyhelm"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/alessandropitocchi/lazyhelm/releases/download/v0.2.2/lazyhelm_Darwin_x86_64.tar.gz"
      sha256 "ee790c06336e5ed0db5d3d1cfcf7b1970aef743327fa9922d092dea022ee394f"

      def install
        bin.install "lazyhelm"
      end
    end
    on_arm do
      url "https://github.com/alessandropitocchi/lazyhelm/releases/download/v0.2.2/lazyhelm_Darwin_arm64.tar.gz"
      sha256 "7bd5a852afe596325b764b8e7c59dcf5d3c4b178a1ca9ff786a3b0e6d892b0e3"

      def install
        bin.install "lazyhelm"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alessandropitocchi/lazyhelm/releases/download/v0.2.2/lazyhelm_Linux_x86_64.tar.gz"
        sha256 "7e87de699fac3580495e268e7443932a8e6316965d24b28185cb6db8d184977a"

        def install
          bin.install "lazyhelm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alessandropitocchi/lazyhelm/releases/download/v0.2.2/lazyhelm_Linux_arm64.tar.gz"
        sha256 "6c3300a833d58123e31bc45ad98542f86ed6c9ef34ade6ec2c85568e5817d842"

        def install
          bin.install "lazyhelm"
        end
      end
    end
  end

  test do
    output = shell_output("#{bin}/lazyhelm --version")
    assert_match "lazyhelm version", output
  end
end
