# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyhelm < Formula
  desc "A terminal UI for browsing and managing Helm charts"
  homepage "https://github.com/alessandropitocchi/lazyhelm"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/alessandropitocchi/lazyhelm/releases/download/v0.2.1/lazyhelm_Darwin_x86_64.tar.gz"
      sha256 "24c18f2378c45c97d2a0877d45ddbd20376c47b9511d3646f9e52561e7a3aeaa"

      def install
        bin.install "lazyhelm"
      end
    end
    on_arm do
      url "https://github.com/alessandropitocchi/lazyhelm/releases/download/v0.2.1/lazyhelm_Darwin_arm64.tar.gz"
      sha256 "184c3c45fbf91ceb4bd11b6ae4297429eb69dae4055c7b07f56ae076a3c63f39"

      def install
        bin.install "lazyhelm"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alessandropitocchi/lazyhelm/releases/download/v0.2.1/lazyhelm_Linux_x86_64.tar.gz"
        sha256 "ffbcfe6c8b3e8dfe7fbe5ac88d8d6243aebc18952b27d0617852d097be809e91"

        def install
          bin.install "lazyhelm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alessandropitocchi/lazyhelm/releases/download/v0.2.1/lazyhelm_Linux_arm64.tar.gz"
        sha256 "12367061a2dccb3b80938df6ad34b14ba847948df346620c7f1798d04e7ee84d"

        def install
          bin.install "lazyhelm"
        end
      end
    end
  end

  test do
    output = shell_output("#{bin}/lazyhelm --version")
    assert_match "lazyhelm version", output
  end
end
