# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyhelm < Formula
  desc "A terminal UI for browsing and managing Helm charts"
  homepage "https://github.com/alessandropitocchi/lazyhelm"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/alessandropitocchi/lazyhelm/releases/download/v0.3.0/lazyhelm_Darwin_x86_64.tar.gz"
      sha256 "cfe3f6fcf829b212707f91683b8cd5c1dcd8f84873a16706aa49c9c546607049"

      def install
        bin.install "lazyhelm"
      end
    end
    on_arm do
      url "https://github.com/alessandropitocchi/lazyhelm/releases/download/v0.3.0/lazyhelm_Darwin_arm64.tar.gz"
      sha256 "78c3b224f10e1e5350ad73914240627c476369bb918cd61c45e20d0f35376e32"

      def install
        bin.install "lazyhelm"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alessandropitocchi/lazyhelm/releases/download/v0.3.0/lazyhelm_Linux_x86_64.tar.gz"
        sha256 "5af64e34c782684e425c462062355e03eab02b8a4a7d08510d4b609671d8c4a6"

        def install
          bin.install "lazyhelm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alessandropitocchi/lazyhelm/releases/download/v0.3.0/lazyhelm_Linux_arm64.tar.gz"
        sha256 "53ebdbf1c3a6efa5475be711d806f105b7ad02b8c74290a52f4ee56e9b9f1d7c"

        def install
          bin.install "lazyhelm"
        end
      end
    end
  end

  test do
    output = shell_output("#{bin}/lazyhelm --version")
    assert_match "lazyhelm version", output
  end
end
